name: GitHub Actions Demo pipeline
run-name: ${{ github.actor }} is trying to set up pipeline
on: [push, workflow_dispatch]
jobs:
  CI-Pipeline-GitHub-Actions:
    name: ci-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run prettier
      - run: npm run typecheck
      - run: npm run test
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ inputs.name }}
          path: dist/${{ runner.temp }}/artifact.tar
          retention-days: ${{ inputs.retention-days }}
          if-no-files-found: error