name: GitHub Actions Demo pipeline
run-name: ${{ github.actor }} is trying to set up pipeline
on: [push, workflow_dispatch]
jobs:
  CI-Pipeline-GitHub-Actions:
    name: ci-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run prettier
      - run: npm run typecheck
      - run: npm run test
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
  CD-Pipeline-GitHub-Actions:
      needs: [CI-Pipeline-GitHub-Actions]
      outputs:
        page-url: ${{ steps.deployment.outputs.page_url }}
      name: cd-pipeline
      runs-on: ubuntu-latest
      permissions:
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Deploy pages
          id: deployment
          uses: actions/deploy-pages@v4
  smoke-test:
      needs: CD-Pipeline-GitHub-Actions
      runs-on: ubuntu-latest
      timeout-minutes: 3
      strategy:
        matrix:
          browser-name: [firefox, chromium]
      steps:
           - name: Check out repository
             uses: actions/checkout@v4

           - name: Set up node 20
             uses: actions/setup-node@v4
             with:
                  node-version: 20

           - name: Install dependencies
             run: npm ci

           - name: Install Playwright Browsers
             run:
                npx playwright install ${{ matrix.browser-name }}

           - name: Run Playwright tests
             run:
                npx playwright test --project ${{ matrix.browser-name }}
             env:
              PLAYWRIGHT_BASE_URL: ${{ needs.CD-Pipeline-GitHub-Actions.outputs.page-url }}

           - uses: actions/upload-artifact@v4
             if: always()
             with:
              name:
                  playwright-report-${{ matrix.browser-name }}
              path: playwright-report/
              retention-days: 1
