name: GitHub Actions Demo pipeline
run-name: ${{ github.actor }} is trying to set up pipeline
on: [push, workflow_dispatch]
jobs:
  CI-Pipeline-GitHub-Actions:
    name: ci-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run prettier
      - run: npm run typecheck
      - run: npm run test
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  CD-Pipeline-GitHub-Actions:
      needs: [ci-pipeline]
      name: cd-pipeline
      runs-on: ubuntu-latest
      permissions:
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Deploy pages
          id: deployment
          uses: actions/deploy-pages@v4
